# https://taskfile.dev

version: "3"

vars:
  BUILDER: buildx-multi-arch
  IMAGE: kameshsampath/rust-builder

tasks:
  
  prepare-buildx:
    desc: prepare the docker buildx environment
    cmds:
      - docker buildx inspect "{{.BUILDER}}" || docker buildx create --name="{{.BUILDER}}" --driver=docker-container --driver-opt=network=host
    silent: true
  
  image:
    desc: build the rust builder image that will be used with ci task. The builder can build targets for linux arm64/amd64
    deps:
      - prepare-buildx
    cmds:
      - docker buildx build --no-cache --builder="{{.BUILDER}}" -t "{{.IMAGE}}" --platform=linux/arm64 --platform=linux/amd64 --push -f docker/Dockerfile.zig.builder docker

  